from pathlib import Path
import re
R=Path.cwd()
p=R/'assets/webapp/index.html'; s=p.read_text()
old="async function navigate(p){window.EduWorkspace.dispose();chatLayout();cleanupChannel();S.page=p;S.group=null;S.direct=null;const box=U.q('#page',app());box.className='content';U.qa('[data-nav]',app()).forEach(x=>x.classList.toggle('active',x.dataset.nav===p));box.innerHTML='<div class=\"loading\">Loading…</div>';try{const c=workspaceContext();if(p==='groups'||p==='people'||p==='chats')await window.EduWorkspace.chat(c,p==='groups'?'groups':p==='people'?'direct':'all');else if(p==='forum')await window.EduWorkspace.forum(c);else if(p==='saved')await window.EduWorkspace.saved(c);else if(p==='meetings')await renderMeetings();else if(p==='notifications')await window.EduWorkspace.notifications(c);else if(p==='profile')await renderProfile();else if(p==='admin'&&isAdmin())await renderAdmin();else await window.EduWorkspace.chat(c,'all');}catch(e){box.innerHTML=`${pageHead('Could not open this page')}<div class=\"card card-pad\"><p class=\"danger-text\">${U.esc(U.errorText(e))}</p><p>If this mentions a missing database function or column, apply the included REVISION4_DATABASE_UPDATE.sql once.</p><button class=\"btn\" onclick=\"location.reload()\">Reload</button></div>`;console.error(e)}}"
new=old.replace("async function navigate(p){window.EduWorkspace.dispose()", "async function navigate(p){const nav=window.__ECP_NAV||(window.__ECP_NAV={stack:[],ready:false,suppress:false});const current=S.page;if(nav.ready&&!nav.suppress&&current&&current!==p){nav.stack.push(current);if(nav.stack.length>30)nav.stack.shift();}nav.suppress=false;nav.ready=true;window.EduWorkspace.dispose()").replace("box.className='content';", "box.className='content';box.dataset.page=p;")
if old not in s: raise SystemExit('navigate target missing')
s=s.replace(old,new,1)
s=s.replace("root.className='content workspace-v3 ws-page ws-standard-page';\n  root.innerHTML=`<div class=\"ws-page-heading\"><div><h1>Notifications</h1>","root.className='content workspace-v3 ws-page ws-standard-page ws-notifications-page';\n  root.innerHTML=`<div class=\"ws-page-heading\"><div><h1>Notifications</h1>",1)
pat=re.compile(r"  async function comments\(post\)\{.*?\n  \}\n  function postMenu",re.S)
rep=r'''  async function comments(post,initialReply=null){let off=0,all=[],reply=initialReply;const r=U.modal({title:'Discussion',wide:true,body:`<h3>${U.esc(post.title)}</h3><p class="ws-post-body">${W.rich(post.body)}</p><div id="ws-comments"></div><button id="comments-more" class="ws-more">More comments</button><form id="comment-form" class="ws-comment-form"><p id="reply-to" hidden></p><textarea id="comment-body" class="textarea" maxlength="4000" placeholder="Write a comment…"></textarea><label class="btn">Photo / video<input id="comment-media" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime"></label><button class="btn primary">Post comment</button></form>`});
   const setReply=(id,names)=>{reply=id||null;const label=U.q('#reply-to',r),input=U.q('#comment-body',r);if(!reply){label.hidden=true;input.placeholder='Write a comment…';return;}const item=all.find(x=>x.id===reply),who=names[item?.author_id]?.full_name||'Member';label.hidden=false;label.innerHTML=`Replying to <b>${U.esc(who)}</b> · <button type="button" class="text-btn" id="cancel-reply">Cancel</button>`;U.q('#cancel-reply',label).onclick=()=>setReply(null,names);input.placeholder=`Reply to ${who}…`;input.focus();};
   const loadComments=async(reset=false)=>{if(reset){all=[];off=0;}const data=W.data(await sb.from('forum_comments').select('*').eq('post_id',post.id).order('created_at').order('id').range(off,off+39));if(!r.isConnected)return;all.push(...data);off+=data.length;const names=await c.namesFor(all.map(x=>x.author_id)),children=new Map();for(const x of all){const k=x.parent_id||'root';if(!children.has(k))children.set(k,[]);children.get(k).push(x);}const render=(x,d=0)=>{const person=names[x.author_id]||{full_name:'Member'},kids=children.get(x.id)||[];return `<article class="ws-comment ${d?'reply':''}" style="margin-left:${Math.min(d,3)*30}px">${W.avatar(person.full_name,person.avatar_path)}<div><b>${U.esc(person.full_name)}</b>${window.EduPresence.badge(x.author_id)}<time>${W.time(x.created_at)}</time>${d?'<small>Reply</small>':''}<p>${W.rich(x.body)}</p>${W.attachment(x,'forum-media')}<button class="text-btn" data-reply="${x.id}">Reply</button>${x.author_id===S.user.id?`<button class="text-btn" data-edit-comment="${x.id}">Edit</button>`:''}${x.author_id===S.user.id||c.can('forum.moderate')?`<button class="text-btn danger-text" data-delete-comment="${x.id}">Delete</button>`:''}</div></article>${kids.map(k=>render(k,d+1)).join('')}`};const roots=all.filter(x=>!x.parent_id||!all.some(y=>y.id===x.parent_id));U.q('#comments-more',r).hidden=data.length<40;U.q('#ws-comments',r).innerHTML=roots.map(x=>render(x)).join('')||'<p>No comments yet.</p>';W.photos(r,sb);W.files(r,sb);U.qa('[data-reply]',r).forEach(b=>b.onclick=()=>setReply(b.dataset.reply,names));U.qa('[data-delete-comment]',r).forEach(b=>b.onclick=W.run(async()=>{if(!window.confirm('Delete this comment and its replies?'))return;W.data(await sb.from('forum_comments').delete().eq('id',b.dataset.deleteComment));await loadComments(true);await load();}));U.qa('[data-edit-comment]',r).forEach(b=>b.onclick=W.run(async()=>{const x=all.find(v=>v.id===b.dataset.editComment),body=window.prompt('Edit comment',x.body);if(!body?.trim())return;W.data(await sb.from('forum_comments').update({body:body.trim()}).eq('id',x.id).eq('author_id',S.user.id));await loadComments(true);}));if(reply)setReply(reply,names);};
   U.q('#comments-more',r).onclick=W.run(()=>loadComments());U.q('#comment-form',r).onsubmit=W.run(async e=>{e.preventDefault();const input=U.q('#comment-body',r),picker=U.q('#comment-media',r),button=U.q('#comment-form button',r),file=picker.files[0];if(button.disabled||(!input.value.trim()&&!file))return;button.disabled=true;let path,saved=false;try{if(file)path=await c.uploadForumMedia(file);W.data(await sb.from('forum_comments').insert({post_id:post.id,author_id:S.user.id,parent_id:reply,body:input.value.trim(),...(path?{image_path:path}:{})}));saved=true;input.value='';picker.value='';}catch(error){if(path&&!saved)await sb.storage.from('forum-images').remove([path]);throw error;}finally{button.disabled=false;}reply=null;U.q('#reply-to',r).hidden=true;input.placeholder='Write a comment…';await loadComments(true);await load();});await loadComments();
  }
  function postMenu'''
s,n=pat.subn(rep,s,1)
if n!=1: raise SystemExit('comments target missing')
s=s.replace("<time>${W.time(comment.created_at)}</time></div></article>`}).join('')}<button type=\"button\" class=\"ws-fb-view-comments\" data-comment=\"${id}\">","<time>${W.time(comment.created_at)}</time><button type=\"button\" class=\"ws-fb-inline-reply\" data-preview-reply=\"${comment.id}\">Reply</button></div></article>`}).join('')}<button type=\"button\" class=\"ws-fb-view-comments\" data-comment=\"${id}\">",1)
s=s.replace("W.photos(box,sb);U.qa('[data-show-reactors]',box).forEach", "W.photos(box,sb);U.qa('[data-preview-reply]',box).forEach(b=>b.onclick=W.run(()=>comments(posts.find(x=>x.id===id),b.dataset.previewReply)));U.qa('[data-show-reactors]',box).forEach",1)
css='''<style id="ecp-v126-ui">#page.ws-notifications-page .ws-panels-toggle{display:none!important}.ws-fb-inline-reply{display:block;border:0;background:none;color:var(--ws-blue);font-size:10px;font-weight:700;padding:3px 0 0 8px}.ws-comment-form #reply-to{margin:0 0 8px;padding:8px 10px;border-radius:12px;background:var(--ws-soft);font-size:12px}.ws-comment.reply{border-left:2px solid var(--ws-line);padding-left:8px}</style>'''
s=s.replace('<script src="native-mobile-patch.js"></script>',css+'<script src="native-mobile-patch.js"></script>',1);p.write_text(s)

p=R/'assets/webapp/native-mobile-patch.js';s=p.read_text()
s=s.replace("if(active&&/^(INPUT|TEXTAREA|SELECT)$/.test(active.tagName)&&\n       (keyboardActive||document.documentElement.classList.contains('ecp-chat-input-focus'))){\n      active.blur();\n      return true;\n    }","if(active&&active===composerInput()){active.blur();return true;}\n    if(active&&/^(INPUT|TEXTAREA|SELECT)$/.test(active.tagName)&&(keyboardActive||document.documentElement.classList.contains('ecp-chat-input-focus'))){active.blur();return true;}",1)
back_override=r'''\n(()=>{\n  'use strict';\n  if(!window.EduNative)return;\n  const prior=window.EduMobileBack;\n  window.EduMobileBack=()=>{\n    const root=document.querySelector('#page');\n    const active=document.activeElement;\n    const composer=document.querySelector('#message-input,#dm-text,#chat-input');\n    // Inner Messenger flow always wins: keyboard -> conversation/list.\n    if(active&&composer&&active===composer){active.blur();return true;}\n    if(document.querySelector('.modal:not(.hidden),dialog[open]')||root?.classList.contains('conversation-open')||root?.classList.contains('direct-workspace')||(root?.querySelector('#group-body')&&root?.classList.contains('chat-workspace'))){\n      if(typeof prior==='function'&&prior())return true;\n    }\n    const current=root?.dataset?.page||'';\n    const nav=window.__ECP_NAV||(window.__ECP_NAV={stack:[],ready:true,suppress:false});\n    const go=(target,reset=false)=>{if(!target||target===current)return false;if(reset)nav.stack.length=0;nav.suppress=true;if(typeof window.navigate==='function'){window.navigate(target);return true;}return false;};\n    if(current==='notifications'||current==='saved')return go('chats',true);\n    if(['chats','groups','people'].includes(current))return go('forum',true);\n    if(current==='forum')return false;\n    while(nav.stack?.length){const target=nav.stack.pop();if(target&&target!==current)return go(target,false);}\n    if(current)return go('forum',true);\n    return typeof prior==='function'?prior():false;\n  };\n})();\n'''\nif 'v1.2.6 final Android back override' not in s:\n s += "\\n// v1.2.6 final Android back override\\n"+back_override+"\\n"\naddon='''\n  // v1.2.6 Messenger-style send: keep IME focused until Android Back.\n  let ecpSendTouchAt=0;const ecpSendSelector='#ws-send button[type="submit"],#dm-form button[type="submit"],#chat-form button[type="submit"],.ws-composer button[type="submit"],.composer button[type="submit"]';\n  document.addEventListener('pointerdown',e=>{const button=e.target.closest?.(ecpSendSelector),input=composerInput();if(!button||!input||document.activeElement!==input)return;e.preventDefault();ecpSendTouchAt=Date.now();const form=button.closest('form');requestAnimationFrame(()=>{try{input.focus({preventScroll:true})}catch{input.focus()}if(form&&!button.disabled)form.requestSubmit(button);settleBottom();});},true);\n  document.addEventListener('click',e=>{if(Date.now()-ecpSendTouchAt<700&&e.target.closest?.(ecpSendSelector)){e.preventDefault();e.stopImmediatePropagation();}},true);\n'''
s=s.replace('\n})();\n',addon+'\n})();\n',1);p.write_text(s)

p=R/'lib/features/meetings/meeting_room_page.dart';s=p.read_text().replace('  bool expandedVideo=false;','  bool expandedVideo=false;\n  bool controlsExpanded=false;',1)
a=s.index('  Widget _bottomControls() {'); b=s.index('\n  @override\n  void dispose()',a)
block='''  Widget _bottomControls() {\n    final extra=<Widget>[\n      callControl(speaker?Icons.volume_up:Icons.volume_off,'Speaker',busy?null:()=>_run(() async{speaker=!speaker;await backend.setSpeaker(speaker);if(mounted)setState((){});}),active:speaker),\n      callControl(Icons.desktop_windows_outlined,backend.screenEnabled?'Stop share':'Share',busy?null:()=>_run(toggleScreen),active:backend.screenEnabled),\n      callControl(Icons.radio_button_checked,recording?'Stop':'Record',busy?null:()=>_run(toggleRecording),active:recording),\n      callControl(Icons.near_me_outlined,'Pointer',togglePointer,active:pointerMode),callControl(Icons.people_outline,'People',showPeople),callControl(Icons.chat_bubble_outline,'Chat',meetingChat),callControl(Icons.headset_mic_outlined,'Devices',showDevices)];\n    return SafeArea(top:false,child:Padding(padding:const EdgeInsets.fromLTRB(8,0,8,7),child:Column(mainAxisSize:MainAxisSize.min,children:[\n      AnimatedSize(duration:const Duration(milliseconds:190),curve:Curves.easeOutCubic,alignment:Alignment.bottomCenter,child:controlsExpanded?Container(width:double.infinity,margin:const EdgeInsets.only(bottom:8),padding:const EdgeInsets.fromLTRB(10,13,10,9),decoration:BoxDecoration(color:const Color(0xF2181C22),borderRadius:BorderRadius.circular(26),border:Border.all(color:Colors.white12),boxShadow:const[BoxShadow(color:Colors.black54,blurRadius:24,offset:Offset(0,10))]),child:Wrap(alignment:WrapAlignment.center,runAlignment:WrapAlignment.center,spacing:4,runSpacing:9,children:extra)):const SizedBox.shrink()),\n      Container(padding:const EdgeInsets.fromLTRB(5,8,5,6),decoration:BoxDecoration(color:const Color(0xEA11151A),borderRadius:BorderRadius.circular(30),border:Border.all(color:Colors.white12),boxShadow:const[BoxShadow(color:Colors.black54,blurRadius:20,offset:Offset(0,8))]),child:Row(mainAxisAlignment:MainAxisAlignment.spaceEvenly,children:[\n        callControl(backend.micEnabled?Icons.mic:Icons.mic_off,'Mic',busy?null:()=>_run(()=>backend.microphone(!backend.micEnabled)),active:backend.micEnabled),\n        callControl(backend.cameraEnabled?Icons.videocam:Icons.videocam_off,'Camera',busy?null:()=>_run(()=>backend.camera(!backend.cameraEnabled,lowBandwidth:lowBandwidth)),active:backend.cameraEnabled),\n        callControl(Icons.call_end,'End',busy?null:leave,danger:true),\n        callControl(controlsExpanded?Icons.keyboard_arrow_down:Icons.keyboard_arrow_up,controlsExpanded?'Less':'More',()=>setState(()=>controlsExpanded=!controlsExpanded),active:controlsExpanded)])\n    )])));\n  }\n'''
s=s[:a]+block+s[b:];p.write_text(s)
p=R/'pubspec.yaml';s=re.sub(r'^version:.*$','version: 1.2.6+25',p.read_text(),flags=re.M);p.write_text(s)
print('Applied EduChatPro v1.2.6')
